// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Linq;

namespace SegueTestApp
{
	public partial class TestViewController : UIViewController
	{

        public string Argument
        {
            get;
            set;
        }
		public TestViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var lbl = this.View.Subviews.OfType<UILabel>().ElementAt(0);

            if (!string.IsNullOrEmpty(Argument))
                lbl.Text = Argument;
        }


	}
}
